### ISSUE TITLE
Parameterize the "home" link in maptool

### ISSUE THREAD

**Issue by machristie** [SciGaP/simccs-maptool#35]
When clicking on the Maptool map icon on the right side, it would be good if it went to /maptool/test on the beta site, but /maptool on the production site.

**Comment by machristie** [comment]
@webgisdeveloper, since we have the beta and the production deployments, maybe we could have a separate branch (called dev?) for the beta site. Then when we're ready to move the new code to production we can merge dev to master and deploy.  What do you think?

**Comment by webgisdeveloper** [comment]
Good idea.Jun 
-------- Original message --------From: Marcus Christie <notifications@github.com> Date: 10/18/19  3:57 PM  (GMT-05:00) To: SciGaP/simccs-maptool <simccs-maptool@noreply.github.com> Cc: Jun Wang <junwang001@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [SciGaP/simccs-maptool] Parameterize the "home" link in maptool (#35) @webgisdeveloper, since we have the beta and the production deployments, maybe we could have a separate branch (called dev?) for the beta site. Then when we're ready to move the new code to production we can merge dev to master and deploy.  What do you think?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/SciGaP/simccs-maptool/issues/35?email_source=notifications\u0026email_token=ABSWBILTPRPSB5M2U7NUWMLQPIIJ3A5CNFSM4JCLUSAKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEBVXN3Y#issuecomment-543913711",
"url": "https://github.com/SciGaP/simccs-maptool/issues/35?email_source=notifications\u0026email_token=ABSWBILTPRPSB5M2U7NUWMLQPIIJ3A5CNFSM4JCLUSAKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEBVXN3Y#issuecomment-543913711",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by webgisdeveloper** [comment]
won't fix, use branch instead
